applications:
  ticketingsystem:
    configs: {
      }
    dockerConfigJson: AgCCFFkpYq1gmEkIiMj3MiiGU+9L2dWxG4XTyou6D+7LZ0l4GdJqFb1OrG/wRqk2Pa6+zrA0lQd0FtOaekAApEwngFIkRmt4Jt39+lySyttmNaUShZKL2gvr+abM8zeFwV0MxKwg/sC0HBfeJLPo0eQOFXZ2Qs3ZjeSBBDkH1W2UbtPXg3uFYGB/7uPC6vhbjwHKUVzac9Vdn/y9UGUg7d8xFzJ1nuRfvZrhIdfEkNeXUnKaTQTH2EgRTi5Cm/zTgrwaw6yn9nB+K+Jc9d1z0PufWpYRac/KS5hsPkRx7ZBNg8F0Z9GLUH6E/AkoXTO7hxo/U002xDFQoZMOg5J4ZEb+bAPQl4yQX2uAzKuhE++i8ZxAV5pgm3vZkfzBaIEza7fUGKJatX08K0skdvBDfPQJs2caZVLuIJ084dSBohkTkCir+YCVhjIhlGWXo8upuoT/QvnXuz1ZPA6LViT1Z8Jg5JmHV9itobi27Zt3pclBGvWmV8gBiFbJnxIXOTkjafM8flu1e2WMIsthw4tN0cBUvQnG7WDj0W8wwpx7oKvcxfHl5W6Urg/vPIEbYH2PE948tH7tCo8H5lHzSMFFcLdOXRPO8tzbF2yFhYeLimq33npz8jA7M2LqwV30KiOgjiAFUg3+0w9Zy2+EWI/Gec5DQdcCDA2pt4cCKpKJopnqSLtDkZoJVMXgpDXRs/5BgXMakiO6g0i0IgWCBkRZSuswRu1xSbZW8TN+np/mZVPCUkl/xySydH5LDfdI9zzIz1USJMVXf3F9bT3lCNkTC0NCsU8YaqVb4A0ehidx/aqfpLNLOAQ9BdYMdpSYn1C1wn+ge8zdTreUjaa2JvpZNBPkUy/Zxg==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: ticketing-system
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: 1.0.1
    volumes: {
      }
  alerts:
    configs: {
      }
    dockerConfigJson: AgB0VrsyC30tFpn0mw/RAC5vwwrbB4PRnjZLobZXmTyWxhvX6xeFoL1WrL4dTzcl3KaERVaaPjWtc8jVApNWAICGzIcsKf/FMmMNebUfB/AY1WbJF8pfGzqeg5O7jeQdvhFcGG0lzVm6+iegbEL96vEOZ7KW/VYGvqifGGrh2alhhSNajZVlIGagUmqogsAGxtMZ47EKaeHH3V4mYJQPpNPQvcez5xhhWjFFzbMUcGblTayweC6Mig66HkV5N5etFB8EN+WuCd8lk3tec5Nu9unO2DvQl/o2xl+R+rhahn9VAxRUmm0yzwZPLrhhD/cgr70JGMcoUCI/RpfUoRNL1I9QynWc7deZ6p2oVKhNzo9KUdNnImH8A4KQgAIT62Fv2dxO/nd5dd7+wRJ1SfCTZb3rL3aje86Rhh3rxxMZmhMQsF/BwkR6wyOrEkVvoG6UHxFPVNIOnQb5v/UryN3nqlisv5qeYKNwfxQy1aVhxLl8wAV2FWKvugjF8zqkgvKqq8Ka40PASdDKTLLp9N7nuxKov909IOgZtluvG82VR0jMwW1ZbKCeV6Q4mSf9rVMKPg0wYuGHQan9NRXZBrHwIEYj/k4yGLPXtQ2WRSIv9P4HGaGfIqvehdf0UtxEdQIYOckw5T5eTt24yvopSCrYRyVAw4TNBIKWFIhpaVL3OZIkPHBJugmHYgM5UB+NOXk6yQ9cnFl5qkFQgoiihUEbj4IfqhXU4QUnDwkYB38XiN7oT2VVBJU0C2EIE+17gLkvUze92Ij+bSfhzr7KOv0X7GIHow9m3MM7WiosbZi8CyY0sLlhDCGJw+cCNItRwbE56KMrP0nk8jPJMEQH7215W5pPDs9U6Q==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: alerts
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: 1.0.0
    volumes: {
      }
  customersurvey:
    configs: {
      }
    dockerConfigJson: AgASLy1+GsWqMWx0iJhdCEaOBFe8aRx2tCyT0ESMJ5ZFVug9VNLnMgEiTe3azLGgOQSvLXey1Lpgre48FK6OVJzwJK4poStjnURRqmkXyLakKOR6IEClzrmX1vxzLa0NRDTscqtbUuE3XHZR5HoCkiXMwG4sDAbvTJLk+E1fyMt7cZTtE3yGot9Cub8Sa61cwUh8tK3vMhIooabkmr+BXCyf8evIzQ3yJpxRled82+jWyjMdy1cAjwMyWIv1gWleRNctOPa8jTPuSrupKA7bzI94QXkmoTpFIUzoFbsMn5MCzuNnisqnEuC7cHagDfsspnLrvxLbivQu92NmTga0hFd/nfMXjzdNIXQBtg/oVwPwkDqnmZC4VrZloUxR561EPBy7xJfeeWgLg93MQf+l/bEAls1LzDEZFrS6TRn5CtcjglDyaELZSKRavUnpnPpBwn8g+XW0S4FGBx51xnrC+Af7o2QHKTMwdPPEVfJ1ehjs4EiFepH+Gm8bm8IAioGpbLdcpG4uH5FDRLL/Z61aY4isLmSyaO7GQASZOnPoa4YYeAhQQMF6wQl+s+C7tG/zIDuKHgmzl7lV7DevQS3gsNMFVk0KIkibW7lxDxE7h3PlGTKNpXZs7JNqfoj2ahXNIOCaJOOEqIXScRjB7AJidK81fLC9pL7vKFJ9nFBfne1ssi7u1BtrDw1Kbop830nr0272zjj0fV0XEKOYIHG7KKth8CBbC3bUbJTVJ2cyBw7XEy+SuP0q0I+44xCTjbIp/Bxg0gtxJD+3cUo1XlBel6f2M3HGqDSK7Yy2gUyKU+zdZYnWDdY2kqwC2Ub+zVjLmbu1Ah/wTdVfic9nfzzr6GaWPeODHQ==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: customer-survey
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: 1.0.0
    volumes: {
      }
environment: stg
host: ahoy.cluster-02.lsdopen.io
releaseName: lsd-support
releaseVersion: '1.0'
