applications:
  cpspringscaffold:
    configs: {
      }
    dockerConfigJson: AgCF3jaUbJgDgS1xDhCymDXXCLmw4VoQOuuWT48ftzN0wXYDnI60AfEip2NZ6nLfdqAMJiSC9ekYWQlJTErhFoLs92ngtGcXYWgfsaFMmlFO/3COCCgM9MDVwnCrXzfXNwnUQ3mWrI9kYirxl51O9gdZGrqdpuGvWJFgg36/3ZcUy6jtxfTYAFhXKPxltx6YNfGltGDuEHJIf7Df+Cb1Q7i1hgOMXwNC2/mwotxkgSwzJUIXBiUneN8QZFb9io2xxadUMs3HACPczVcTBR7j5xg7cz2TAfiUWVaWRcb53Lkjz3I1UyvD38na+nACtWf+aLSPaSgpkNP1s/NgBn/HZCrdWNeRlZqsBzkSIydQ3ZgAw0aRgsm0/NQDp41nPe1aHd6PFZExDQplmX3HFKCjb/J1vCT/H0gxjWauuV2jmC8N6o/QbueQiF1iBRhoqW7YUrUbaDcPsAx2sp/R+OFR6CM8SxJh1jOwrdUvSxXggayNx+Bix2yN6LbFfb3pEBpHXnwzQrkqT2glhXek+kd/i1ito+iobOevooXGOdkimP+8umK9X2oSVNSDyZ2eyJCF3l+mMBz3XzDmOEwIe8v+7TDIC25kZLW4aBb78D5LtussF30hwVn4di1bahDz4BxHnIm/6KejOLwno944ICwRVlXewgdF+MkO3esBLAVB1gwfsVbS6sGd6mdO1ZAo3Fq/PaRRgVsqvusmiJuIngftzWkHeJ3YBeOK5DdsMgVZEsVOEs+QniQTTToMku1PsdL2Cw5w8aM4gQx5H9H9iQPNY6LwCQrE9mWxNQYMSaVebhpb1x9BFZndR8qxJh1PA5QegJrfQRwI51fjv/XrCnwSKa+4N4LHCw==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: cp-spring-scaffold
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: 1.0.0
    volumes: {
      }
  exporter:
    configs: {
      }
    dockerConfigJson: AgCW8CnPiJn8N4BDlviDuR5mC7rRi2fvhoiFfzBD0fWaOxJSUrHL/xajn/rD7q23DtxXUYQZTNJBm/rsh/EM4jmlyRsENbEkZEdVNy9yHIahOsJHDxp3P9VK4yoHQS30auK875aDm35wPJZOMB3UUAMoHlDoNmWlVzzOi3Bc9BI+HpKpcq8SpccJYEExTlK4hcesHb/3iohwKBXkDagRBNpW1lj3OejYcjpGvzAuD+bGnVQS4wbVGsPb/DAw2mB9yLnz8AwK+XMUW4jEGUnlvlY43l7HsJg38KuGKOAuMSR9VsVwrTwVyDl7F7eEmzaHlx4r1KBovFyd1E8DOIIRfXi3FyORtMfsjsF+Ga+GvM0EyDfbfHcDJnCc29vA2OGpOT78AKq+S6+l3D0+00GqFo2F9GFsBs1jOpZywfwvMhI01soqdfNklRZPan1F1Qn57bYkV0o1D5VZRFswyHR+WFCOuwoo1elPLakJz0S83xZPQZryNWnE3YYFPUq/ENdyI3WI20rLwbMJAQo4Hx+ogYvoZHDm+Qs2CIg0TyC/3EEg2iJZ6WNgSLA3sjWv4axKgWXFbQw8lOVUqzU5NL7NiZZo0i+N2yaWERk6Pd+2Efxl+1OnhA/5y/T7BWdj4rzQKNHdVQJQLVwUH7VuKNqwJiNtGl3/CiBNUESwPLRV+kLjQ2gFGHnyvC+Hx88aW4wGZWez4kDmiMiwHRwiykrRwVNNyrVvKPJ0QEjZxd3ILLuQufIlQgc/P8qwrREjtCLsc5VRHhLkSiOZhMoxqQzvl58AphfFtJpvpeyK/8f3h04Bpy5uQGYS5xSn0UX/HtH7ep4WrtLecvqBj4c5Y7ov5u6YRptj5w==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: exporter
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: 1.0.2
    volumes: {
      }
  customersurvey:
    configs: {
      }
    dockerConfigJson: AgAbkevnX8L7+xAlqWymHBqNkdH4VAq23JDN5CjeiItOpJEoGaZMC6iAvq5OqbZixAXL3R+ouJeO8vGZliH1HB1esBIy9nGLO6/iWkav9w8w4jGjkijQrPFYE35T0LWbBggw6pkwLuJJH+uHveMZ0Ukm4uvYc/Uh/f0rTzwy00O0xGI3qXTomEhpX7UnpiHUQmGebA8dlT4yBt/SQFHSyX+oHOHR0spjtZkBKN/Pvx7WYONLjba1l9fIIR8NGQ3yxiearIfXMnLyf6yw1jLlEiL88o1iwhD8ORcX6I6BvqqnZcqKB+PXMBrj4RQj4u5U6Tzw5O68y2Nx98c1hN/rQncoabfCMKjwwf08j6vIG9aqXJusk8BOMx7SQL4avT+nQTBH+9sWdzT5cuGCHHZVN+VaDUQCmHuZuUUcUT0ZVF2JvV/gJBjzOY1D/4AAyL2TztzYbnuhrmFmlRWXyp1wS7CDoQUEgguxeMDhlQp2SdrTxXWQJSxe/vQUt0VJALUBxtwUjwQX+w2oFLchXvHFOp14lUJN/kNuEL2m0cmj4JpndcO0Gekw0hbuAh46HneswcPMYc6+1KXHvDC11Wid55ceBCfX8uDjyNkfrqGpyZxO92lPiJFRHlnoevff5XbhTpvy0U1/FEiTpe3acK+Mq/Mhf6LFoMyz5O0hvm2Qa8fIBdtmUCPERLGXnYH9dJPxhTvRnwShXxBw2qZIQLuxxvz7omdYIrOANqO2D+/fHi4TlTWI2+cWNS4Der9neZzIcqvlQJ6Q0/Pq5O6jdop+24TA1w40XX5QGeKP9rqRjpR004tgvcphHH4BfoUyK97vkfpABH5WzFVwIQFSsA7LvYn8GIJ5Tg==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: customer-survey
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: 1.0.0
    volumes: {
      }
environment: tst
host: ahoy.cluster-02.lsdopen.io
releaseName: dok-is-great
releaseVersion: '1.1'
