applications:
  calculator:
    configs: {
      }
    dockerConfigJson: AgBLkdhwmt3j9FrdlXQHdMQ9KzKrDtJrlpEUvCR6gjJQD8vjOB5zppeuf+7UcyzcTuISUOETn3OlkgN9rUR+Bjio3uwXZ9XstiDnxWTTVut0sDiJhCKcLXXm5HwfSXH5jJKHDbiyRYV3kn+9jpkd033PYsR9+PfqkLE352PWLQKXILlQ/UPEBzNu7aWPt4un8NWeJB8/471c1W2GdPtnXGPRfVwkeTE8FEl8JVo0NTO/erLXHZkeNoDDzoFOYOxZPDxC2Hvt2xaPjI2sM4YtbKdxwtwTf/IWoMRu1yBWnchEHrcSFXo/En/63K3lkfoUSIO3xM4/4BiMugFHrXSot3MXem0KXcOpxmlziIXHNR5kc+sYO20B/iX2wH2t7kTGZxMFp/jbSPGDXdR6BRR3XMdDFzXQI24QdGBjgUKK/P6sRh+uHvwsXYMBhv7p2aTRMKpMmzGBhn4mFBAs6mGf6eMI4kQNVH0Ztkkseaz19KNPw/je0zWyRO3AJ8SvFdLjgMgeOhstXDmZh8V6cuZw962+OmCNrlNiJ0kx7V1NF3pPEUfXklS7VcOF/MSx+YuBcT+72RAr80QkRkfZ0bw9IpcEQySGxuMQ4jSux0eLSXs/QQFvdQQD8zRJkvMxYfL4ENy4s96E+LNherUhi5Dn+tNOUS30IlTKeCuR+UlNcAiazkmDN8vXo10bOtaBvkqng0kM7OaNuxcnoyWfNgMfA69WTRyyDWUKEoaPK92IUd+rDIWAEm3YC2WVJw0BdPj8NifcdUr9kQPtUfaEn2s/k5IX+nx/xRA2ZHsLli0OW+6m4dVGddeBPysuoR2VmKGQCibHUFp/xt4/VbJVTQXcQ4zPS4Q1XA==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: calculator
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: '1.0'
    volumes: {
      }
  pdfgenerator:
    configs: {
      }
    dockerConfigJson: AgB/a/0+GOl764LjX9AYv2CvmcTsC5Cvidcflqfwn6Z0+ZchUytLHdBYe8AoggKt5+vFvUXissV0PM9LZJP2UhYUAKSHKfHNF9e8d/mM0nO3rP9v4PPO5dCbu/JjscPn9/4kfassdOWF24eOHBJq/7WdesFOnYYy4U4J7UE3igQraRcjHtorv5t8Pa/Dqa5+99mxok4p5ih2aPrUpBZ6UBf3WxNYlp/JCvtPmomRE1Fhd83iTXpDLazgnUiIMVLbthUSsY9dZQJeTrVPQLih4912E7iRVq0dPv9APJ/QSpoCfcWLITC3otKtEPKW9RvHI6qgQ+Pa0am6Qu3STPOlmr3D65CyJcjwu5Q0gCjFTA5iULxbBAa6weZBvnENk6K3RN3YnMuRSvkc/Kl7RnyTwZXsfw3bOz4aTdoz6TWbm35VnxSkICvOa2d3s25ZMW66O+9CAWseOEqRc4y2Ak8IgeJgYWUdPoXug/EIKamC15OnTbB9fTWFGfytRfeNJ/K5k2Y0Y12838iYrG23cDueSZPkArvBCHGuSu7F1NnZ2LqG4ntRz1yNGA5jceNGyIfKmWxJDqseTs8SssVTSDYPsITCc7LzF7wwtWcjNH1m0VEMA3rgkZ4eCrBWSQJvOqvtsKxmu93n7ZUqvSy36w2xKNvy4kLPOJev30Ro3Wp2GWjTQrYn8oPssp/bN/5SVjPBanLASCvOvDiN01Tyozob+W7O0FjtvwDeWAC9nY7cNiqhtY2Jzq4pvRSERudEUmLc672zsUGSJtrOnwRoPX9f0j9L89t6UZ2fdnJdk8+b/rXQLAlDuFor4Yzu6/xI6cx1STptCTTu0rO+jRO7Kp2Zky7GqlSZkQ==
    environmentVariables: {
      }
    image: lsdtrip/cp-spring-scaffold:1.0.63
    name: pdf-generator
    replicas: 1
    secrets: {
      }
    servicePorts: [
      ]
    tls: false
    version: 1.0.5
    volumes: {
      }
environment: uat
host: ahoy.cluster-02.lsdopen.io
releaseName: medical-aid-contribution
releaseVersion: '1.2'
